# Note: For production. For development, use `docker-compose.yml`
version: '3.0'
services:
  geth:
    image: ethereum/client-go
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "geth"
    network_mode: bridge
    ports:
      - 8545:8545
      - 8546:8546
    expose:
      - 8545
      - 8546
      - 30303
    volumes:
      - /srv/ethereum:/root/.ethereum
    restart: unless-stopped
    command: /usr/bin/geth --syncmode "fast" --allow-insecure-unlock --cache 4096 --rpc --rpcaddr 0.0.0.0 --rpcvhosts "geth" --rpcport 8545 --rpccorsdomain "*" --rpcapi personal,web3,eth,net --ws --wsaddr 0.0.0.0  --wsorigins "*" --wsport 8546 --wsapi personal,web3,eth,net
